
import "./globals.css";



export const metadata = {
  title: "Landing page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      
    </head>
      <body
      
      >
        {children}
      </body>
    </html>
  );
}
